[package]
name = "link_gpt_jni"
version = "0.1.2"
edition = "2021"

[lib]
crate_type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
link_gpt = { path = "../link_gpt" }
jni = "0.21.1"
