/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_iashchak_linkgpt_TextGeneration */

#ifndef _Included_eu_iashchak_linkgpt_TextGeneration
#define _Included_eu_iashchak_linkgpt_TextGeneration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_iashchak_linkgpt_TextGeneration
 * Method:    new_text_generation
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_eu_iashchak_linkgpt_TextGeneration_new_1text_1generation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_iashchak_linkgpt_TextGeneration
 * Method:    generate_text
 * Signature: (JLjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_iashchak_linkgpt_TextGeneration_generate_1text
  (JNIEnv *, jobject, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
