/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_iashchak_linkgpt_HelloWorld */

#ifndef _Included_eu_iashchak_linkgpt_HelloWorld
#define _Included_eu_iashchak_linkgpt_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_iashchak_linkgpt_HelloWorld
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_iashchak_linkgpt_HelloWorld_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
