/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_iashchak_linkgpt_Dialog */

#ifndef _Included_eu_iashchak_linkgpt_Dialog
#define _Included_eu_iashchak_linkgpt_Dialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_iashchak_linkgpt_Dialog
 * Method:    to_string
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_iashchak_linkgpt_Dialog_to_1string
  (JNIEnv *, jobject);

/*
 * Class:     eu_iashchak_linkgpt_Dialog
 * Method:    with_system
 * Signature: ()Leu/iashchak/linkgpt/Dialog;
 */
JNIEXPORT jobject JNICALL Java_eu_iashchak_linkgpt_Dialog_with_1system
  (JNIEnv *, jobject);

/*
 * Class:     eu_iashchak_linkgpt_Dialog
 * Method:    add_message
 * Signature: (Leu/iashchak/linkgpt/Message;)Leu/iashchak/linkgpt/Dialog;
 */
JNIEXPORT jobject JNICALL Java_eu_iashchak_linkgpt_Dialog_add_1message
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
