/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_iashchak_linkgpt_Message */

#ifndef _Included_eu_iashchak_linkgpt_Message
#define _Included_eu_iashchak_linkgpt_Message
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_iashchak_linkgpt_Message
 * Method:    to_string
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eu_iashchak_linkgpt_Message_to_1string
  (JNIEnv *, jobject, jlong);

/*
 * Class:     eu_iashchak_linkgpt_Message
 * Method:    from_string
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_eu_iashchak_linkgpt_Message_from_1string
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eu_iashchak_linkgpt_Message
 * Method:    from_tuple
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_eu_iashchak_linkgpt_Message_from_1tuple
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
