name: Rust CI
on: [ push ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Include all "Tier 1 with Host Tools" targets and "Tier 2 with Host Tools" targets for Windows and macOS,
        # excluding *-pc-windows-msvc, which requires cross-toolchains. Goal is one option per OS per architecture.
        # https://doc.rust-lang.org/rustc/platform-support.html
        # https://github.com/cross-rs/cross#supported-targets
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        include:
          # 32-bit (i686)
          # i686-apple-darwin is Tier 3.
          - build: linux-32-bit
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
            command: cross
            lib_ext: .so
            app_ext: ""
          - build: windows-32-bit
            os: ubuntu-latest
            target: i686-pc-windows-gnu
            command: cross
            lib_ext: .dll
            app_ext: .exe
          # 64-bit (x86)
          - build: linux-64-bit
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cross
            lib_ext: .so
            app_ext: ""
          - build: macos-64-bit
            os: macos-latest
            target: x86_64-apple-darwin
            command: cargo
            lib_ext: .dylib
            app_ext: .app
          - build: windows-64-bit
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            command: cross
            lib_ext: .dll
            app_ext: .exe
          # 64-bit (ARM)
          # aarch64-pc-windows-gnullvm is Tier 3.
          - build: macos-arm
            os: macos-latest
            target: aarch64-apple-darwin
            command: cargo
            lib_ext: .dylib
            app_ext: .app
          - build: linux-arm
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            command: cross
            lib_ext: .so
            app_ext: ""
          # Android config
          - name: android-arm
            os: ubuntu-latest
            target: aarch64-linux-android
            command: cross
            lib_ext: .so
            app_ext: ""
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - run: cargo install cross --git https://github.com/cross-rs/cross

      - run: ${{ matrix.command }} build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.build }}
          path:  |
            target/${{ matrix.target }}/release/link_gpt_app${{ matrix.app_ext }}
            target/${{ matrix.target }}/release/liblink_gpt_jni${{ matrix.lib_ext }} 
