on: [ push ]
name: Cross CI
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # Linux config
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: cross
          # Android config
          - name: android-arm
            runner: ubuntu-latest
            target: aarch64-linux-android
            command: cross
          # Windows config
          - build: windows-64-bit
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            command: cross
          # MacOS config
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
            command: cross
          # MacOS ARM config
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
            command: cross

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}
      - run: cargo install cross --git https://github.com/cross-rs/cross
      - run: ${{ matrix.command }} build --release --target ${{ matrix.target }}